/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    QomoHeader: (typeof import("./src/components/QomoHeader/index.vue"))["default"];
    QomoLogin: (typeof import("./src/components/QomoLogin/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
